SERVICE_ROLE_ARN = 'ServiceRoleArn'
LAMBDA_BASIC_EXECUTION_ROLE = 'AWSLambdaBasicExecutionRole'
SERVICE_ROLE = 'ServiceRole'
CREATE_LAMBDA = 'CreateOrder'
GET_LAMBDA = 'GetOrder'
DELETE_LAMBDA = 'DeleteOrder'
LIST_LAMBDA = 'ListOrders'
TABLE_NAME = 'orders'
IDEMPOTENCY_TABLE_NAME = 'Idempotency'
TABLE_NAME_OUTPUT = 'DbOutput'
IDEMPOTENCY_TABLE_NAME_OUTPUT = 'IdempotencyDbOutput'
APIGATEWAY = 'Apigateway'
MONITORING_TOPIC = 'MonitoringTopic'
GW_RESOURCE = 'orders'
SWAGGER_RESOURCE = 'swagger'
SWAGGER_CSS_RESOURCE = 'swagger.css'
SWAGGER_JS_RESOURCE = 'swagger.js'
SWAGGER_URL = 'SwaggerURL'
LAMBDA_LAYER_NAME = 'common'
API_HANDLER_LAMBDA_MEMORY_SIZE = 128  # MB
API_HANDLER_LAMBDA_TIMEOUT = 10  # seconds
POWERTOOLS_SERVICE_NAME = 'POWERTOOLS_SERVICE_NAME'
SERVICE_NAME = 'Orders'
SERVICE_NAME_TAG = 'service'
OWNER_TAG = 'owner'
METRICS_NAMESPACE = 'orders_kpi'
METRICS_DIMENSION_KEY = 'service'
POWERTOOLS_TRACE_DISABLED = 'POWERTOOLS_TRACE_DISABLED'
POWER_TOOLS_LOG_LEVEL = 'LOG_LEVEL'
BUILD_FOLDER = '.build/lambdas/'
COMMON_LAYER_BUILD_FOLDER = '.build/common_layer'
ENVIRONMENT = 'dev'
CONFIGURATION_NAME = 'my_conf'
CONFIGURATION_MAX_AGE_MINUTES = '5'  # time to store app config conf in the cache before refetching it

# Lambda Managed Instances
MANAGED_INSTANCE_LAMBDA = 'ManagedInstanceOrder'
MANAGED_INSTANCE_CAPACITY_PROVIDER = 'OrdersCapacityProvider'
MANAGED_INSTANCE_OPERATOR_ROLE = 'CapacityProviderOperatorRole'
MANAGED_INSTANCE_LAMBDA_ROLE = 'ManagedInstanceLambdaRole'
MANAGED_INSTANCE_VPC = 'ManagedInstanceVpc'
MANAGED_INSTANCE_SECURITY_GROUP = 'ManagedInstanceSg'
MANAGED_INSTANCE_OPERATOR_POLICY = 'AWSLambdaManagedEC2ResourceOperator'
MANAGED_INSTANCE_MEMORY_SIZE = 2048  # MB
MANAGED_INSTANCE_EPHEMERAL_STORAGE = 512  # MB
MANAGED_INSTANCE_MAX_VCPU = 100
MANAGED_INSTANCE_VPC_CIDR = '10.0.0.0/16'
MANAGED_INSTANCE_AVAILABILITY_ZONES = ['us-east-1a', 'us-east-1b']
MANAGED_INSTANCE_MEMORY_GIB_PER_VCPU = 2  # allowed: 2-8; RAM-to-vCPU ratio used to select instance type (2=c-family, 4=m-family, 8=r-family)
MANAGED_INSTANCE_MAX_CONCURRENCY_PER_ENV = 4  # allowed: 1-1600; caps concurrent invocations per environment. Python runs one process per invocation, so lower values reduce memory contention within MemorySize.
MANAGED_INSTANCE_MIN_EXECUTION_ENVIRONMENTS = 3  # 3 is the minimum and default
MANAGED_INSTANCE_MAX_EXECUTION_ENVIRONMENTS = 4
